export const CREATE = "CREATE";
export const UPDATE = "UPDATE";
export const DELETE = "DELETE";
export const FETCH_ALL = "FETCH_ALL";
export const FETCH_DEPARTMENT_ALL = "FETCH_DEPARTMENT_ALL";
export const FETCH_DEPARTMENT_CREATE = "FETCH_DEPARTMENT_CREATE";
export const FETCH_DEPARTMENT_UPDATE = "FETCH_DEPARTMENT_UPDATE";
export const FETCH_DEPARTMENT_DELETE = "FETCH_DEPARTMENT_DELETE";
